FROM python:3.11-slim

WORKDIR /opt/ngsqc

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY db/ /opt/ngsqc/db/
COPY init-db/ /opt/ngsqc/init_db/

RUN python -m pip install --upgrade pip && \
    pip install pandas psycopg2-binary

RUN mkdir -p /data/processed /logs

ENTRYPOINT ["python", "/opt/ngsqc/db/upload_CSV.py"]
